--[[
  <## JSON of Dependencies
     [ ]
  ##>
--]]
function onLoad(savedData)
  print("Example Board succesfully configured!")
end

function underConstruction()
    print("Example used to test other things...")
end

function rulesButtonBehaviour()  -- Toogle the rules window (on Global)
    print("At example: rules")
    if UI.getAttribute("Example.RulesWindow", "active")=="true"
      then UI.hide("Example.RulesWindow")
      else UI.show("Example.RulesWindow")
     end
end
